#!/usr/bin/env python3
"""
Generate player locale artifacts from canonical locale/<lang>.yaml files:
  - locale/<lang>           (key = value, settings-style lines)
  - webui/src/locales/<lang>.json
  - src/l10n_defaults_gen.c (embedded English defaults for bsearch fallback; generated —
    exclude from coverage expectations, see codecov.yml / Makefile test-coverage)
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML is required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def flatten(obj: object, prefix: str = "") -> list[tuple[str, str]]:
    """Flatten nested dicts to dot keys; leaf values must be scalars."""
    out: list[tuple[str, str]] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            if not isinstance(k, str):
                raise ValueError(f"non-string key {k!r}")
            key = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict):
                out.extend(flatten(v, key))
            elif isinstance(v, (str, int, float, bool)):
                out.append((key, str(v)))
            elif v is None:
                continue
            else:
                raise ValueError(f"unsupported value type at {key}: {type(v)}")
    else:
        raise ValueError(f"expected dict at {prefix!r}, got {type(obj)}")
    return out


def c_escape(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def escape_kv_value(v: str) -> str:
    """Escape newlines and backslashes so each entry is exactly one line."""
    return v.replace("\\", "\\\\").replace("\r", "\\r").replace("\n", "\\n")


def write_kv_file(pairs: list[tuple[str, str]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/locale_codegen.py — do not edit by hand.",
        "# Rebuild: make locale-codegen",
        "",
    ]
    for k, v in sorted(pairs, key=lambda x: x[0]):
        # One line per key; value may contain '=' — only first '=' is delimiter when parsing
        lines.append(f"{k} = {escape_kv_value(v)}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


JSON_FILE_COMMENT = (
    "Generated by scripts/locale_codegen.py from locale/<lang>.yaml — do not edit by hand. "
    "Rebuild: make locale-codegen"
)


def write_json(pairs: list[tuple[str, str]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    d = dict(sorted(pairs, key=lambda x: x[0]))
    # _comment is a conventional non-locale key; keep first for human readers.
    out: dict[str, str] = {"_comment": JSON_FILE_COMMENT}
    out.update(d)
    text = json.dumps(out, ensure_ascii=False, indent=2) + "\n"
    path.write_text(text, encoding="utf-8")


def write_defaults_c(en_pairs: list[tuple[str, str]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    sorted_pairs = sorted(en_pairs, key=lambda x: x[0])
    lines = [
        "/* Generated by scripts/locale_codegen.py — do not edit by hand. */",
        '/* Rebuild: make locale-codegen */',
        "",
        '#include "l10n.h"',
        "#include <stdlib.h>",
        "#include <string.h>",
        "",
        "typedef struct {",
        "	const char *key;",
        "	const char *value;",
        "} BarL10nDefaultPair_t;",
        "",
        "static const BarL10nDefaultPair_t bar_l10n_defaults[] = {",
    ]
    for k, v in sorted_pairs:
        lines.append(f'\t{{ "{c_escape(k)}", "{c_escape(v)}" }},')
    lines.append("};")
    lines.append("")
    lines.append("#define BAR_L10N_DEFAULT_COUNT \\")
    lines.append(f"\t(sizeof (bar_l10n_defaults) / sizeof (bar_l10n_defaults[0]))")
    lines.append("")
    lines.append("static int bar_l10n_default_cmp (const void *a, const void *b) {")
    lines.append("\tconst BarL10nDefaultPair_t *pa = (const BarL10nDefaultPair_t *) a;")
    lines.append("\tconst BarL10nDefaultPair_t *pb = (const BarL10nDefaultPair_t *) b;")
    lines.append("\treturn strcmp (pa->key, pb->key);")
    lines.append("}")
    lines.append("")
    lines.append("const char *BarL10nDefaultLookup (const char *key) {")
    lines.append("\tif (!key) {")
    lines.append("\t\treturn NULL;")
    lines.append("\t}")
    lines.append("\tBarL10nDefaultPair_t probe = { key, NULL };")
    lines.append("\tconst BarL10nDefaultPair_t *found = bsearch (")
    lines.append("\t\t&probe, bar_l10n_defaults, BAR_L10N_DEFAULT_COUNT,")
    lines.append("\t\tsizeof (bar_l10n_defaults[0]), bar_l10n_default_cmp);")
    lines.append("\tif (found) {")
    lines.append("\t\treturn found->value;")
    lines.append("\t}")
    lines.append("\treturn NULL;")
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def yaml_lang_name(path: Path) -> str:
    return path.stem


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent)
    args = ap.parse_args()
    root: Path = args.repo_root
    locale_dir = root / "locale"
    yaml_files = sorted(locale_dir.glob("*.yaml"))
    if not yaml_files:
        print(f"No locale/*.yaml files in {locale_dir}", file=sys.stderr)
        return 1

    en_yaml = locale_dir / "en.yaml"
    if not en_yaml.is_file():
        print(f"Missing canonical {en_yaml}", file=sys.stderr)
        return 1

    en_raw = yaml.safe_load(en_yaml.read_text(encoding="utf-8"))
    if not isinstance(en_raw, dict):
        print("en.yaml must be a mapping at root", file=sys.stderr)
        return 1
    en_pairs = flatten(en_raw)

    write_defaults_c(en_pairs, root / "src" / "l10n_defaults_gen.c")

    for ypath in yaml_files:
        lang = yaml_lang_name(ypath)
        raw = yaml.safe_load(ypath.read_text(encoding="utf-8"))
        if not isinstance(raw, dict):
            print(f"{ypath}: root must be a mapping", file=sys.stderr)
            return 1
        pairs = flatten(raw)
        write_kv_file(pairs, root / "locale" / lang)
        write_json(pairs, root / "webui" / "src" / "locales" / f"{lang}.json")

    print("locale-codegen:", ", ".join(yaml_lang_name(p) for p in yaml_files))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
