name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install APT packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libao-dev libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev \
          libcurl4-gnutls-dev libgcrypt20-dev libjson-c-dev libpth-dev libasound2-dev \
          libwebsockets-dev pkg-config build-essential
    - name: Install BLAS/LAPACK (not cached due to symlink issues)
      run: sudo apt-get install -y libblas-dev liblapack-dev
    - name: Build pianobar
      run: make

